---
title: "Placement Tree Analysis"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---
```{r Initialization}
source("data-loading.R")
```

# Executions

The following executions are evaluated in this report

```{r Executions}
executions <- loadExecutions()
executions

nodes = c("client")#, "public", "purchasing", "production", "employees") # Nodes to assess
source("group-labels.R")
```

# Labeling

```{r labels}
applyLabels <- function(data) {
  d <- data %>% left_join(groupLabels, "group") %>%
           mutate(resources = replace(replace(resources,
                                              resources == "hetero141120.5", "heterogeneous"),
                                      resources == "homo122222", "homogeneous"),
         costFunction = replace(replace(replace(replace(costFunction,
                                                        costFunction == "5secqlSum", "\u03A3BP"),
                                                costFunction == "5secqlProd", "\u03A0BP"),
                                        costFunction == "5hlOlProd", "\u03A0BL"),
                                costFunction == "5hlOlSum", "\u03A3BL"),
         selectivity = replace(replace(selectivity,
                                       selectivity == "est", "estimated"),
                               selectivity == "event", "precise"),
         query = gsub("query", "", query),
         costOperator = substr(costFunction, 0, 1),
         costCombination = case_when(substr(costFunction, 2, nchar(costFunction)) == "BP" ~ "priority",
                                     substr(costFunction, 2, nchar(costFunction)) == "BL" ~ "load"),
         groupLabel = paste(resources, costOperator, costCombination, placement, selectivity))
  d$query <- factor(d$query, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))
  d$costOperator <- factor(d$costOperator, levels = c("\U03A3", "\U03A0"))
  d$resources <- factor(d$resources, levels = c("homogeneous", "heterogeneous"))
  
  return(d)
}


plotTheme <- function() {
  return(theme(legend.position = "none",#c(case_when(legendRight ~ 0.91, TRUE ~ 0.1), 0.9),
              plot.title = element_text(size = 9, margin = margin(0, 0, 0, 0, "cm")),
              axis.title.x = element_text(size = 9, margin = margin(0, 0, 0, 0, "cm")),
              axis.title.y = element_text(size = 9, margin = margin(0, 0, 0, 0, "cm")),
              axis.text.x = element_text(size = 8),
              axis.text.y = element_text(size = 8),
              strip.text.x = element_text(margin = margin(0, 0, 0, 0, "cm")),
              strip.text.y = element_text(margin = margin(0, 0, 0, 0, "cm")),
              legend.title = element_blank(),
              legend.background = element_rect(fill=alpha('blue', 0)),
              legend.spacing.x = unit(0.1, "cm"),
              legend.key.width = unit(0.3, "cm"),
              legend.key.height = unit(0, "cm")))
}

onlyPrioLoad <- function(data) {
  return(data %>% filter(costFunction %in% c("\u03A3BP", "\u03A0BP", "\u03A0BL", "\u03A3BL")))
}
```


```{r}
### Read in all data
rawData <<- loadData(executions, "config") %>% filter(property == "placement")

operators <- rawData %>% as.tbl_json(json.column = "value") %>%
  enter_object("operators") %>%
  gather_array() %>% 
  spread_values(operatorId = jnumber("id"), operatorName = jstring("operatorName"), selectivity = jnumber("selectivity"), operatorLoad = jnumber("load"), outgoingLink = jnumber("outgoingLink")) %>%
  transmute(execution, operatorId, operatorName, selectivity, operatorLoad, outgoingLink)

hosts <- rawData %>% as.tbl_json(json.column = "value") %>%
  enter_object("hosts") %>%
  gather_array() %>% 
  spread_values(hostId = jnumber("id"), hostName = jstring("name")) %>%
  transmute(execution, hostId, hostName)

links <- rawData %>% as.tbl_json(json.column = "value") %>%
  enter_object("links") %>%
  gather_array() %>% 
  spread_values(sender = jnumber("sender"), receiver = jnumber("receiver"), linkLoad = jnumber("load")) %>%
  transmute(execution, sender, receiver, linkLoad)

solutions <- rawData %>% as.tbl_json(json.column = "value") %>%
  enter_object("solutions") %>%
  gather_array(column.name = "solution") %>%
  enter_object("placements") %>%
  gather_array() %>%
  spread_values(operatorId = jnumber("operator"), hostId = jnumber("host")) %>%
  transmute(execution, solution, operatorId, hostId) %>%
  left_join(hosts, by=c("execution", "hostId")) %>%
  left_join(operators, by=c("execution", "operatorId"))

placements <- rawData %>% as.tbl_json(json.column = "value") %>% 
  spread_values(cost = jstring("cost"), selectedSolution = jnumber("selectedSolution"), duration = jnumber("duration"), timedOut = jlogical("timedOut")) %>% 
  inflateExecutionInfo() %>% applyLabels() %>% onlyPrioLoad() %>%
  left_join(
    (solutions %>% group_by(execution) %>% transmute(solution) %>% distinct %>% count %>% ungroup %>% rename(solutions = n)), 
    by = "execution") %>% arrange(execution)


placements
```

# Statistics

```{r}
distinctSolutions <- solutions %>%
  filter(!(operatorName %in% c("re-classification", "de-classification"))) %>%
  group_by(solution, execution) %>%
  unite("placed", operatorId, hostId) %>%
  summarize(placement = str_c(placed, collapse=",")) %>%
  ungroup() %>% group_by(execution) %>%
  summarize(distinctSolutions = n_distinct(placement)) %>% 
  ungroup()

distinctOperatorPlacements <- 
  solutions %>%
  filter(!(operatorName %in% c("re-classification", "de-classification"))) %>%
  transmute(execution, solution, operatorId, hostId) %>%
  spread(operatorId, hostId) %>%
  group_by(execution) %>%
  summarise_all(n_distinct) %>%
  ungroup() %>%
  gather("operatorId", "placements", 3:28) %>%
  filter(placements > 1) %>%
  group_by(execution) %>%
  summarize(distinctOperatorPlacements = n_distinct(operatorId)) %>% 
  ungroup()

placementStatistics <- placements %>%
  left_join(distinctSolutions, by = "execution") %>%
  left_join(distinctOperatorPlacements, by = "execution")
placementStatistics[is.na(placementStatistics)] <- 0
placementStatistics

plotPlacementStats <- function(data, title) {
  colors <- c("cyan", "yellow", "red")
  return(ggplot(data, aes(y=selectivity, x=query)) +
          ggtitle(title) +
          geom_tile(aes(fill = distinctSolutions), color= "black") +
          geom_text(aes(label = paste(distinctSolutions, distinctOperatorPlacements, sep="\n"), lineheight = 0.7)) +
          ylab("Selectivity") +
          facet_grid(costCombination ~ costOperator, scales="free") +
          scale_fill_gradientn(colours=brewer.pal(7, "OrRd"), limits=c(1, 8)) +
          plotTheme() +
          theme(
              axis.title.x=element_text(size = 8, hjust=-0.12, margin = margin(t=-0.35, unit = "cm"))
              ))
}

placementStatsHomoPrivPlot <- plotPlacementStats(placementStatistics %>% filter(resources == "homogeneous" & placement == "private"), expression(paste("Placement Solutions (", S[h], ", ", P[private], ")")))
# Export
ggsave("stability-homo-private.pdf", width = 10, height = 5, units = "cm", device = cairo_pdf)
placementStatsHeteroPrivPlot <- plotPlacementStats(placementStatistics %>% filter(resources == "heterogeneous" & placement == "private"), expression(paste("Placement Solutions (", S[v], ", ", P[private], ")")))
# Export
ggsave("stability-hetero-private.pdf", width = 10, height = 5, units = "cm", device = cairo_pdf)

placementStatsHomoOptPlot <- plotPlacementStats(placementStatistics %>% filter(resources == "homogeneous" & placement == "optimal"), expression(paste("Placement Solutions (", S[h], ", ", P[optimal], ")")))
# Export
ggsave("stability-homo-optimal.pdf", width = 10, height = 5, units = "cm", device = cairo_pdf)
placementStatsHeteroOptPlot <- plotPlacementStats(placementStatistics %>% filter(resources == "heterogeneous" & placement == "optimal"), expression(paste("Placement Solutions (", S[v], ", ", P[optimal], ")")))
# Export
ggsave("stability-hetero-optimal.pdf", width = 10, height = 5, units = "cm", device = cairo_pdf)

placementStatsHomoPrivPlot
placementStatsHomoOptPlot
placementStatsHeteroPrivPlot
placementStatsHeteroOptPlot
```


# Graphs

```{r}
nodes <- solutions %>% transmute(execution,
                                 solution,
                                 label = operatorName,
                                 hostId,
                                 operatorId) %>% distinct %>% 
  rowid_to_column("id")

link_operators <- nodes %>%
  transmute(execution, senderSolution = solution, senderNode = id, sender = operatorId, senderHost = hostId) %>%
  right_join(
    links,
    by = c("execution", "sender")
  ) %>%
  left_join(
    nodes %>% transmute(execution, receiverSolution = solution, receiverNode = id, receiver = operatorId, receiverHost = hostId),
    by = c("execution", "receiver")
  ) %>% filter(senderSolution == receiverSolution)

edges <- link_operators %>% transmute(execution,
                                      rel = "data", 
                                      from = senderNode,
                                      to = receiverNode) %>% distinct %>%
  rowid_to_column("id")
  
for (i in 1:nrow(placements)) {
  placement <- placements %>% slice(i)
  
  create_graph(
    directed = TRUE,
    nodes_df = (nodes %>% filter(execution == placement[1, "execution"])),
    edges_df = (edges %>% filter(execution == placement[1, "execution"]))) %>%
    colorize_node_attrs(node_attr_from = hostId, node_attr_to = fillcolor, palette = "Set1", alpha = 50) %>%
    colorize_node_attrs(node_attr_from = hostId, node_attr_to = color, palette = "Set1") %>%
    set_node_attrs(node_attr = fontcolor, values = "#000000") %>%
    render_graph(layout = "tree", title = paste(placement[1, "query"], placement[1, "groupLabel"], "(Selected", placement[1, "selectedSolution"], ")")) %>% print
}
```
